name: "S3 Sync"
description: "Sync a directory to an AWS S3 repository using role assigned to runner."
author: samcrudge
runs:
  using: docker
  image: Dockerfile
branding:
  icon: refresh-cw
  color: green
